bump dxda version to 1.49
dnanexus/dxWDL pull request #465
Opened 2020-10-06 20:55 UTC by jdidion

* bump dxda to 0.5.4
* increase retries for API calls to 10

2020-10-06 21:08 UTC, commandlinegirl requested changes
The PR message says it also increases API retries but the update is not here

2020-10-07 00:36 UTC, jdidion commented
oops - forgot to push. it's there now

2020-10-07 00:37 UTC, jdidion commented
and I also messed up - this is a change to master, not v1. I'll do a separate PR there.

2020-10-07 04:22 UTC, commandlinegirl approved these changes

2020-10-07 04:22 UTC, merged